"use strict";
const $=id=>document.getElementById(id), state={recording:false,watchId:null,startTime:null,timer:null,points:[],markers:[],photos:[],last:null,tile:null};
const ids=["speed","avgSpeed","maxSpeed","altitude","maxAltitude","heading","cardinal","accuracy","duration","distance","climb","sink","stripMaxAlt","stripMaxSpeed"];
const map=L.map("map",{zoomControl:true}).setView([47.28,15.97],9); let route=L.polyline([],{color:"#29c6ff",weight:5,opacity:.95}).addTo(map), currentMarker=null, markerLayer=L.layerGroup().addTo(map);
const tiles={osm:["https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'],topo:["https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png",'Kartendaten &copy; OpenStreetMap, SRTM | Karte &copy; OpenTopoMap']};
function setTiles(name="osm"){if(state.tile)map.removeLayer(state.tile);const t=tiles[name]||tiles.osm;state.tile=L.tileLayer(t[0],{attribution:t[1],maxZoom:19}).addTo(map);localStorage.setItem("tileStyle",name)} setTiles(localStorage.getItem("tileStyle")||"osm");
function showToast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove("show"),2600)}
function fmtTime(s){s=Math.max(0,Math.floor(s));return [s/3600,s/60,s].map((v,i)=>String(Math.floor(v)%(i?60:999)).padStart(2,"0")).join(":")}
function hav(a,b){const R=6371,rad=x=>x*Math.PI/180,dlat=rad(b.lat-a.lat),dlon=rad(b.lng-a.lng);const q=Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function cardinal(d=0){return ["N","NO","O","SO","S","SW","W","NW"][Math.round(d/45)%8]}
function totalDistance(){return state.points.slice(1).reduce((s,p,i)=>s+hav(state.points[i],p),0)}
function updateUI(){const ps=state.points,last=ps.at(-1),speeds=ps.map(p=>p.speed||0),alts=ps.map(p=>p.alt||0),dist=totalDistance();if(last){$("speed").textContent=Math.round(last.speed||0);$("altitude").textContent=Math.round(last.alt||0);$("heading").textContent=Math.round(last.heading||0)+"°";$("cardinal").textContent=cardinal(last.heading);$("accuracy").textContent="±"+Math.round(last.accuracy||0)}$("avgSpeed").textContent=speeds.length?Math.round(speeds.reduce((a,b)=>a+b,0)/speeds.length):0;$("maxSpeed").textContent=$("stripMaxSpeed").textContent=Math.round(Math.max(0,...speeds));$("maxAltitude").textContent=$("stripMaxAlt").textContent=Math.round(Math.max(0,...alts));$("distance").textContent=dist.toFixed(2).replace(".",",");const elapsed=state.startTime?(Date.now()-state.startTime)/1000:0;$("duration").textContent=fmtTime(elapsed);$("elapsedLabel").textContent=state.recording?"Aufzeichnung läuft seit "+fmtTime(elapsed):"Noch keine Aufzeichnung";if(ps.length>1){const a=ps.at(-2),dt=(last.ts-a.ts)/1000,rate=dt>0?(last.alt-a.alt)/dt:0;$("climb").textContent=(rate>0?rate:0).toFixed(1).replace(".",",");$("sink").textContent=(rate<0?rate:0).toFixed(1).replace(".",",")}route.setLatLngs(ps.map(p=>[p.lat,p.lng]));drawChart();$("recordSummary").textContent=`Aktuell: ${fmtTime(elapsed)} · ${dist.toFixed(2)} km · ${ps.length} GPS-Punkte`;}
function drawChart(){const c=$("altitudeChart"),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;const x=c.getContext("2d");x.scale(d,d);const w=r.width,h=r.height;x.clearRect(0,0,w,h);x.strokeStyle="#28445a";for(let i=1;i<5;i++){x.beginPath();x.moveTo(0,i*h/5);x.lineTo(w,i*h/5);x.stroke()}const a=state.points.map(p=>p.alt||0);if(a.length<2)return;const min=Math.min(...a),max=Math.max(...a),range=max-min||1;x.beginPath();a.forEach((v,i)=>{const px=i/(a.length-1)*w,py=h-8-(v-min)/range*(h-18);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle="#17b9ff";x.lineWidth=2;x.stroke();}
function gpsPoint(pos){const c=pos.coords,p={lat:c.latitude,lng:c.longitude,alt:c.altitude??(state.last?.alt||0),speed:Math.max(0,(c.speed||0)*3.6),heading:c.heading||0,accuracy:c.accuracy,ts:pos.timestamp};state.last=p;if(state.recording)state.points.push(p);if(!currentMarker)currentMarker=L.circleMarker([p.lat,p.lng],{radius:8,color:"#fff",fillColor:"#f23",fillOpacity:1}).addTo(map);else currentMarker.setLatLng([p.lat,p.lng]);if(!state.recording)map.setView([p.lat,p.lng],14);$("gpsStatus").textContent="⌁ GPS AKTIV";updateUI();}
function gpsError(e){$("gpsStatus").textContent="⌁ GPS FEHLER";showToast(e.code===1?"Standortzugriff wurde nicht erlaubt.":"GPS-Position derzeit nicht verfügbar.")}
function beginWatch(){if(!navigator.geolocation)return showToast("Geolocation wird von diesem Browser nicht unterstützt.");if(state.watchId!==null)navigator.geolocation.clearWatch(state.watchId);state.watchId=navigator.geolocation.watchPosition(gpsPoint,gpsError,{enableHighAccuracy:$("highAccuracy").checked,maximumAge:1000,timeout:15000})}
function toggleRecording(){state.recording?stopRecording():startRecording()}
function startRecording(){state.recording=true;state.startTime=Date.now();state.points=[];state.markers=[];state.photos=[];route.setLatLngs([]);markerLayer.clearLayers();$("liveDot").classList.add("on");$("recordingLabel").textContent="LIVE AUFZEICHNUNG";$("recordBtn").textContent="■ AUFZEICHNUNG BEENDEN";$("recordBtn2").textContent="■ Aufzeichnung beenden";state.timer=setInterval(updateUI,1000);beginWatch();showToast("Aufzeichnung gestartet")}
function stopRecording(){state.recording=false;clearInterval(state.timer);$("liveDot").classList.remove("on");$("recordingLabel").textContent="BEREIT";$("recordBtn").textContent="▶ AUFZEICHNUNG STARTEN";$("recordBtn2").textContent="▶ Aufzeichnung starten";if(state.points.length){const f={id:Date.now(),date:new Date().toISOString(),duration:Date.now()-state.startTime,distance:totalDistance(),maxAltitude:Math.max(...state.points.map(p=>p.alt||0)),maxSpeed:Math.max(...state.points.map(p=>p.speed||0)),points:state.points,markers:state.markers,photoCount:state.photos.length};const logs=getLogs();logs.unshift(f);localStorage.setItem("balloonFlights",JSON.stringify(logs));showToast("Flug im lokalen Flugbuch gespeichert");renderLog();renderStats()}else showToast("Keine GPS-Punkte gespeichert");updateUI()}
function mark(type){if(!state.recording||!state.last)return showToast("Zuerst Aufzeichnung starten und GPS-Position abwarten.");const m={...state.last,type,label:type==="landing"?"Landung":"Markierung"};state.markers.push(m);L.marker([m.lat,m.lng]).bindPopup(m.label).addTo(markerLayer);showToast(m.label+" gesetzt")}
function getLogs(){try{return JSON.parse(localStorage.getItem("balloonFlights")||"[]")}catch{return[]}}
function download(name,data,type="application/json"){const a=document.createElement("a"),url=URL.createObjectURL(new Blob([data],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function toGPX(f){const pts=f.points.map(p=>`<trkpt lat="${p.lat}" lon="${p.lng}"><ele>${p.alt||0}</ele><time>${new Date(p.ts).toISOString()}</time></trkpt>`).join("");return `<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="Ballonflugbuch Web"><trk><name>Ballonfahrt ${new Date(f.date).toLocaleDateString("de-AT")}</name><trkseg>${pts}</trkseg></trk></gpx>`}
function renderLog(){const logs=getLogs(),box=$("logList");box.innerHTML=logs.length?logs.map(f=>`<article class="log-item"><div><h3>${new Date(f.date).toLocaleString("de-AT")}</h3><p>${fmtTime(f.duration/1000)} · ${f.distance.toFixed(2)} km · max. ${Math.round(f.maxAltitude)} m · ${f.points.length} Punkte</p></div><div class="mini-actions"><button data-gpx="${f.id}">GPX</button><button data-del="${f.id}">Löschen</button></div></article>`).join(""):'<div class="empty">Noch keine Fahrten gespeichert.</div>';box.querySelectorAll("[data-gpx]").forEach(b=>b.onclick=()=>{const f=logs.find(x=>x.id==b.dataset.gpx);download(`ballonfahrt-${f.id}.gpx`,toGPX(f),"application/gpx+xml")});box.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{localStorage.setItem("balloonFlights",JSON.stringify(logs.filter(x=>x.id!=b.dataset.del)));renderLog();renderStats()})}
function renderStats(){const l=getLogs(),sum=k=>l.reduce((s,f)=>s+(f[k]||0),0),max=k=>Math.max(0,...l.map(f=>f[k]||0));$("statsGrid").innerHTML=`<div class="stat"><span>Fahrten</span><b>${l.length}</b></div><div class="stat"><span>Gesamtdistanz</span><b>${sum("distance").toFixed(1)} km</b></div><div class="stat"><span>Gesamtzeit</span><b>${fmtTime(sum("duration")/1000)}</b></div><div class="stat"><span>Größte Höhe</span><b>${Math.round(max("maxAltitude"))} m</b></div>`}
async function loadWeather(){if(!state.last)return showToast("Zuerst Standort aktivieren.");$("weatherDetails").textContent="Wetter wird geladen …";try{const {lat,lng}=state.last,r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lng}&current=temperature_2m,wind_speed_10m,wind_direction_10m,weather_code&wind_speed_unit=kmh`),j=await r.json(),c=j.current;$("weatherMini").textContent=`☀ ${Math.round(c.temperature_2m)}°C`;$("weatherDetails").textContent=`Temperatur: ${c.temperature_2m} °C\nWind: ${c.wind_speed_10m} km/h aus ${c.wind_direction_10m}°\nMesszeit: ${new Date(c.time).toLocaleString("de-AT")}`;}catch{$("weatherDetails").textContent="Wetterdaten konnten nicht geladen werden."}}
function page(name){document.querySelectorAll(".page").forEach(n=>n.classList.toggle("active",n.id===`page-${name}`));document.querySelectorAll(".nav-btn").forEach(n=>n.classList.toggle("active",n.dataset.page===name));if(name==="overview")setTimeout(()=>map.invalidateSize(),50)}
document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>page(b.dataset.page));document.querySelectorAll("[data-goto]").forEach(b=>b.onclick=()=>page(b.dataset.goto));$("recordBtn").onclick=$("recordBtn2").onclick=toggleRecording;$("landingBtn").onclick=()=>mark("landing");$("markerBtn").onclick=()=>mark("marker");$("locateBtn").onclick=()=>{beginWatch();if(state.last)map.setView([state.last.lat,state.last.lng],15)};$("fitBtn").onclick=()=>state.points.length&&map.fitBounds(route.getBounds(),{padding:[30,30]});$("weatherBtn").onclick=loadWeather;$("exportAllBtn").onclick=()=>download("ballonflugbuch-export.json",JSON.stringify(getLogs(),null,2));$("tileStyle").value=localStorage.getItem("tileStyle")||"osm";$("tileStyle").onchange=e=>setTiles(e.target.value);$("highAccuracy").onchange=()=>beginWatch();$("clearBtn").onclick=()=>{if(confirm("Alle lokal gespeicherten Fahrten wirklich löschen?")){localStorage.removeItem("balloonFlights");renderLog();renderStats();showToast("Lokale Daten gelöscht")}};$("photoInput").onchange=e=>{if(e.target.files[0]){state.photos.push({name:e.target.files[0].name,ts:Date.now()});showToast("Foto zur aktuellen Fahrt vorgemerkt")}};
setInterval(()=>$("clock").textContent=new Date().toLocaleTimeString("de-AT"),1000);window.addEventListener("resize",drawChart);renderLog();renderStats();drawChart();beginWatch();if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));
